export const BRANCH = import.meta.env.GITHUB_REF;
export const BRANCH_NAME = import.meta.env.GITHUB_HEAD_REF;
export const COINBASE_APP_ID = import.meta.env.COINBASE_APP_ID ?? '';
export const COMMIT_SHA = import.meta.env.GITHUB_SHA;
export const IS_DEV_ENV = import.meta.env.WALLET_ENVIRONMENT === 'development';
export const IS_TEST_ENV = import.meta.env.TEST_ENV === 'true';
export const MOONPAY_API_KEY = import.meta.env.MOONPAY_API_KEY ?? '';
export const SEGMENT_WRITE_KEY = import.meta.env.SEGMENT_WRITE_KEY ?? '';
export const SENTRY_DSN = import.meta.env.SENTRY_DSN ?? '';
export const TRANSAK_API_KEY = import.meta.env.TRANSAK_API_KEY ?? '';
export const WALLET_ENVIRONMENT = import.meta.env.WALLET_ENVIRONMENT ?? 'unknown';
export const LEDGER_BITCOIN_ENABLED = import.meta.env.LEDGER_BITCOIN_ENABLED === 'true';
